name: minimercado_app
description: Aplicación de inventario para minimercado

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  velocity_x: ^3.5.0
  http: ^1.1.0  # ✅ VERSIÓN COMPATIBLE CON DART 3.2.0
  image_picker: ^1.0.4
  intl: ^0.18.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
